### ISSUE TITLE
decode/encode Generic

### ISSUE THREAD

**Issue by izgzhen** [purescript/purescript-generics#26]
I'd like to add a feature aiming at decode and encode any instance of `Generic` based on `purescript-json`.

Here are some [experimental hacks](https://github.com/izgzhen/purescript-generics/commit/cecf09f2a4f95458829394d48ccc96a8be799dde).

#### Motivation
Originally, I was thinking about implementation of Template PureScript. Then I found that I have to figure out a way to manipulate AST inside PureScript (e.g. https://github.com/izgzhen/purescript-purescript/blob/master/src/Language/PureScript/AST.purs). Besides, the result of evaluation has to _be sent back_ to the compiler. JSON seems to be a proper intermediate format.

The AST I coded in  https://github.com/izgzhen/purescript-purescript/blob/master/src/Language/PureScript/AST.purs can be derived as `Generic` without much pain. So I started to add `ToJSON` and `FromJSON` for `Generic`.

Besides, it might be useful in other cases.

#### Current status
The upstream dependency [`purescript-json` ](https://github.com/philopon/purescript-json) is maintained by @philopon. I have made a PR to expose the `jsonToValue` function I used in the experimental code.

Some simple tests are passed.

#### Existing problem
The coercion [here](https://github.com/izgzhen/purescript-generics/blob/json/src/Data/Generic.purs#L155 ) is necessary to decode encoded special `Number`s such as `1.0`, since `1.0` will be parsed back to `JInt` thus becoming `SInt` instead of `SNumber`.

I wonder how big the impact will be if such explicit coercion is added.

**Comment by garyb** [comment]
Have you had a look at Argonaut? It already supports encoding/decoding of types with a `Generic` insteance: https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/dfa3559779e300857582d05af0af72dd1b2ddb84/src/Data/Argonaut/Encode.purs#L25-L27

There's a pending PR that will allow the encoding format to be customised too, I'm waiting until we finally get the 0.8 release of the compiler out the door before releasing that though.

**Comment by izgzhen** [comment]
@garyb Wow, it seems like I invented another wheel. Argonaut looks cool, I will try something with it later. Thanks for the hint.

**Comment by garyb** [comment]
Sorry you had to put all that work in first :smile:

Argonaut is split into a few components, you can just require `purescript-argonaut` to get the whole thing: `Json` type & core functions, codecs, traversals & zipper.
