### ISSUE TITLE
Generic GenericSpine instance?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-generics#30]
Where `fromSpine = Just`, and `toSpine = id`. Do you think this would make sense?

**Comment by paf31** [comment]
No, I don't think so. If you did `gShow someSpine`, you'd expect to see the spine, not the value it came from, for example.

**Comment by hdgarrood** [comment]
Ah, of course, yes. And I guess defining this instance 'normally' would be difficult given that it contains functions.

I don't have any reason to want this instance anyway, so I'll close this.
