### ISSUE TITLE
No instance for Ordering

### ISSUE THREAD

**Issue by bsermons** [purescript/purescript-generics#33]
Ran into an error while trying to generic derive a record with an `Ordering` property from Prelude.

**Comment by paf31** [comment]
Yes, we should add an instance for this.

**Comment by bsermons** [comment]
I can send a PR but I'm not sure the correct way to go about it.  Would adding a `SigOrdering` and `SOrdering` constructor be correct or to use the SProd/SigProd similar to here https://github.com/purescript/purescript-generics/pull/28/files ?

**Comment by paf31** [comment]
No, I think we'd just derive an instance here.

**Comment by garyb** [comment]
@bsermons yeah, deriving will work - I asked you to open the issue here as defining it anywhere else would result in an orphaned instance. :)

Well, aside from the Prelude, but the dependencies don't work out that way.

**Comment by garyb** [comment]
I'm happy to make the change, by the way, I'm going through the core libraries again and updating for state of the art 0.9 psc.

**Comment by bsermons** [comment]
Ok great, just wanted to offer help in case you guys were busy on other things.  Thanks for everything.

**Comment by garyb** [comment]
This went into the current v1 release candidate :+1:
