### ISSUE TITLE
readme says documentation is on Pursuit, but I can't seem to find it

### ISSUE THREAD

**Issue by rvion** [purescript/purescript-generics#39]
documentation says 

Module documentation is [published on Pursuit] (http://pursuit.purescript.org/packages/purescript-generics).

but http://pursuit.purescript.org/packages/purescript-generics returns an error

**Comment by garyb** [comment]
This is due to a recent Pursuit update, everything needs re-uploading I think (for now, the old index will be restored by script at some point)... I've done so now, so it's up there again!

**Comment by rvion** [comment]
thanks for the re-upload and for the explanation
