### ISSUE TITLE
Generic instance for Void

### ISSUE THREAD

**Issue by ethul** [purescript/purescript-generics#46]
Would it make sense to have a generic instance for `Void`, similar to the instance for `Unit`?

**Comment by paf31** [comment]
I think so, yes.

**Comment by ethul** [comment]
Is there is a way to get a value of type `Void`? If we wanted to write the instance as below. But maybe there is a better way to write the instance.

```purescript
instance genericVoid :: Generic Void where
     toSpine _ = SVoid
     toSignature _ = SigVoid
     fromSpine SVoid = Just ?void
     fromSpine _ = Nothing
```

**Comment by paf31** [comment]
I think the trick is to define `SVoid` as `| SVoid Void`.

**Comment by garyb** [comment]
Or just `fromSpine _ = Nothing` since a value can't exist for it?

**Comment by paf31** [comment]
Yes, that works too 😄

**Comment by ethul** [comment]
Thanks! Is there a preference for one over the other?

**Comment by paf31** [comment]
I prefer the `SVoid Void` option, only because it makes it clear that that sort of spine is not inhabitable.

**Comment by ethul** [comment]
Sounds good to me. Thanks again.
